name: Simple pipeline to build firmware, flash DUT, and run tests
on: [push]
env:
  LAGER_GATEWAY: helpful-horse

jobs:
  build_flash_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Do lager python
        uses: docker://lagerdata/lager-cli:v0.1.37
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.AKBAR_SECRET_TOKEN }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        with:
          entrypoint: /usr/local/bin/lager
          args: python --passenv API_PASSWORD python_tests/tester.py
