name: Simple pipeline to build firmware, flash DUT, and run tests
on: [push]
env:
  LAGER_GATEWAY: helpful-horse

jobs:
  build_flash_and_run:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        uses: docker://lagerdata/devenv-cortexm@sha256:2742d3fc1d3794d84afbe5aee79a1854a9079a2468d26d083f5d67c98435db3a
        with:
          entrypoint: /bin/bash
          args: -c "exec /usr/local/bin/lager exec build"

      - name: Connect to debugger
        uses: docker://lagerdata/lager-cli:v0.1.35
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.AKBAR_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: connect --device nrf52 --force

      - name: Flash and run
        uses: docker://lagerdata/lager-cli:v0.1.35
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.AKBAR_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: testrun --serial-device /dev/ttyACM0 --hexfile _build/unit-tests/test-suites/test-ledctrl/test-ledctrl.hex
