name: This is my sample workflow
on: [push]
env:
  LAGER_GATEWAY: helpful-horse

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build the code
        uses: docker://lagerdata/devenv-cortexm-minimal
        with:
          entrypoint: /usr/local/bin/lager
          args: exec cmake-build

      - name: Upload the hexfile
        uses: actions/upload-artifact@v2
        with:
          name: hexfile
          path: _build/unit-tests/test-suites/test-example/test-example.hex

  connect:
    runs-on: ubuntu-latest
    steps:    
      - name: Connect to gateway
        uses: docker://lagerdata/lager-cli
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.AKBAR_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: connect --device nrf52 --force

  do_the_testrun:
    runs-on: ubuntu-latest
    needs: [build, connect]
    steps:    
      - name: Download the hexfile
        uses: actions/download-artifact@v2
        with:
          name: hexfile

      - name: Perform a testrun
        uses: docker://lagerdata/lager-cli
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.AKBAR_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: "testrun --hexfile $GITHUB_WORKSPACE/test-example.hex --serial-device /dev/ttyACM0"